services:
  - type: web
    name: evjf-app
    runtime: python
    buildCommand: echo "no build needed"
    startCommand: python3 server.py
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: evjf-data
      mountPath: /opt/render/project/src
      sizeGB: 1
